In [1]:
import numpy as np

In [2]:
my_list = [1,2,3]

In [3]:
arr = np.array(my_list)

In [4]:
arr

array([1, 2, 3])

In [5]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [6]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [9]:
np.zeros(4)

array([0., 0., 0., 0.])

In [10]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
np.ones(3)

array([1., 1., 1.])

In [12]:
np.ones((2,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [15]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [16]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [17]:
np.random.rand(5)

array([0.02615414, 0.65348029, 0.69525692, 0.8848744 , 0.21539898])

In [18]:
np.random.rand(5,5)

array([[0.30771127, 0.31314799, 0.18177873, 0.75931839, 0.30011543],
       [0.79765395, 0.39483502, 0.61625435, 0.15087756, 0.01918397],
       [0.81947512, 0.03575089, 0.89453176, 0.01950992, 0.99553452],
       [0.79171989, 0.91500869, 0.12998455, 0.05453556, 0.41563699],
       [0.38347146, 0.23287076, 0.79087509, 0.91388155, 0.26135735]])

In [20]:
np.random.randn(2)

array([1.44161468, 1.13720755])

In [21]:
np.random.randn(2,3)

array([[-0.47477494,  0.57161402,  0.31166639],
       [-1.55511314,  0.31747229, -1.28155995]])

In [22]:
np.random.randint(0,500)

323

In [23]:
np.random.randint(0,500,12)

array([306,   0, 223,  10,  38, 488,  36,  40, 492, 334, 499,  21])

In [24]:
arr = np.arange(25)

In [25]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [26]:
ranarr = np.random.randint(0,50,10)

In [27]:
ranarr

array([20, 17,  0, 31,  3, 45, 35, 22,  8, 47])

In [28]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [29]:
ranarr.max()

47

In [30]:
ranarr.min()

0

In [31]:
ranarr.argmax()

9

In [32]:
ranarr.argmin()

2

In [34]:
arr.shape

(25,)

In [35]:
arr = arr.reshape(5,5)

In [36]:
arr.shape

(5, 5)

In [37]:
arr.dtype

dtype('int64')

In [38]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
arr[8]

8

In [40]:
arr[1:5]

array([1, 2, 3, 4])

In [41]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [42]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [43]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [44]:
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [45]:
arr = np.arange(0,11)

In [46]:
slice_of_arr = arr[0:6]

In [47]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [48]:
slice_of_arr[:] = 99

In [49]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [50]:
arr_copy = arr.copy()
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [51]:
arr_copy[:] = 100

In [52]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])